plugins {
    id 'java-test-fixtures'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
}

bootJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
//    launchScript() executable jar 생성 옵션
}

dependencies {
    implementation project(":backend-domain")
    implementation project(":backend-application")
    implementation project(":backend-infrastructure")

    implementation("org.springframework.boot:spring-boot-starter-batch")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.batch:spring-batch-test")
}