server:
  port: 9040
  shutdown: graceful

# 스프링 프레임워크 설정
spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    open-in-view: false
#    properties:
#      hibernate.hbm2ddl.auto: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration, org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

logging:
  level:
    root: info
    org.springframework.batch: info
    jdbc:
      sqlonly: off
      sqltiming: off
      audit: off
      connection: off
      resultsettable: off
      resultset: off
