spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

#  redis:
#    host: localhost
#    port: 6379

  # AutoConfiguration 설정
#  autoconfigure:
#    exclude: com.integralblue.log4jdbc.spring.Log4jdbcAutoConfiguration
