# Common application properties for server-api
server:
  port: 9010
  shutdown: graceful

spring:
  profiles:
    group:
      default:
        - infra-develop
      test:
        - infra-develop
      release:
        - infra-release