# Common application properties for server-api
server:
  port : 9010
  shutdown: graceful
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    group:
      default:
        - infra-develop
      test:
        - infra-develop
      release:
        - infra-release

logging:
  config: classpath:logback/logback.xml