spring:
  cache:
    type: redis
    redis:
      time-to-live: 10

---
spring:
  config:
    activate:
      on-profile: infra-develop
  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: infra-release
  data:
    redis:
      host:
      port:
      password: